repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==24.12.12
          - flake8-comprehensions==3.16.0
          - flake8-docstrings==1.7.0
          - mccabe==0.7.0
          - pycodestyle==2.12.1
          - pyflakes==3.2.0
        args:
          - --max-line-length=100

  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.3
    hooks:
      - id: pylint
        args:
        - --disable=import-error
        - --disable=too-many-arguments
        - --disable=too-many-positional-arguments
        - --disable=too-many-locals
        - --output-format=colorized
